repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--disable-rule=terraform_required_providers --disable-rule=terraform_required_version
      - id: terraform_docs
        args:
          - --args=--hide=requirements
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Get the latest from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  -   repo: https://github.com/Yelp/detect-secrets
      rev: v1.4.0
      hooks:
        -   id: detect-secrets
            args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.6
    hooks:
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--skip-check CKV_AWS_300
          - --args=--skip-check CKV2_AWS_16
          - --args=--skip-check CKV_AWS_18
          - --args=--skip-check CKV2_AWS_62
          - --args=--skip-check CKV_AWS_144
          - --args=--skip-check CKV_AWS_109
          - --args=--skip-check CKV_AWS_111
          - --args=--skip-check CKV_AWS_356
          - --args=--skip-check CKV2_GHA_1
          - --args=--skip-check CKV_AWS_108
          - --args=--skip-check CKV_AWS_107
